import { safeLoad, safeSave } from './cache';

const SESSIONS_STORAGE_KEY = 'weathergpt-saved-sessions';

/**
 * Clean and truncate the first user query to create a legible session title.
 */
export function generateSessionTitle(firstQueryText) {
  if (!firstQueryText || typeof firstQueryText !== 'string') {
    return 'Meteorological Consultation';
  }
  // Strip leading emojis and whitespace
  const clean = firstQueryText.replace(/^[\u{1F000}-\u{1FFFF}\u{2600}-\u{27BF}\s]*/u, '').trim();
  if (!clean) return 'Meteorological Consultation';
  // Truncate to 48 characters with ellipsis if too long
  return clean.length > 48 ? clean.substring(0, 48).trim() + '…' : clean;
}

/**
 * Format IST timestamp for session headers
 */
export function formatIstTimestamp(date = new Date()) {
  try {
    return new Intl.DateTimeFormat('en-IN', {
      timeZone: 'Asia/Kolkata',
      day: '2-digit',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
    }).format(date) + ' IST';
  } catch {
    return new Date().toLocaleTimeString();
  }
}

/**
 * Load all saved sessions sorted by updatedAt descending.
 */
export function getSavedSessions() {
  const sessions = safeLoad(SESSIONS_STORAGE_KEY, []);
  if (!Array.isArray(sessions)) return [];
  return sessions.sort((a, b) => (b.updatedAt || 0) - (a.updatedAt || 0));
}

/**
 * Upsert a session into localStorage.
 * If the session already exists, updates it and bumps updatedAt.
 * If new, prepends it.
 */
export function saveSession(session) {
  if (!session || !session.id || !Array.isArray(session.messages) || session.messages.length === 0) {
    return getSavedSessions();
  }

  const existingSessions = getSavedSessions();
  const existingIdx = existingSessions.findIndex(s => s.id === session.id);

  const updatedSession = {
    ...session,
    updatedAt: Date.now(),
    messageCount: session.messages.length,
    title: session.title || generateSessionTitle(session.messages.find(m => m.role === 'user')?.text || ''),
    preview: session.preview || session.messages.slice().reverse().find(m => m.role === 'assistant')?.text || '',
  };

  let newSessions;
  if (existingIdx >= 0) {
    newSessions = [...existingSessions];
    newSessions[existingIdx] = updatedSession;
  } else {
    newSessions = [updatedSession, ...existingSessions];
  }

  // Cap saved sessions at 50 to maintain fast localStorage performance
  if (newSessions.length > 50) {
    newSessions = newSessions.slice(0, 50);
  }

  safeSave(SESSIONS_STORAGE_KEY, newSessions);
  return newSessions;
}

/**
 * Delete a specific session by ID.
 */
export function deleteSession(sessionId) {
  const existing = getSavedSessions();
  const filtered = existing.filter(s => s.id !== sessionId);
  safeSave(SESSIONS_STORAGE_KEY, filtered);
  return filtered;
}

/**
 * Clear all saved sessions.
 */
export function clearAllSessions() {
  safeSave(SESSIONS_STORAGE_KEY, []);
  return [];
}

/**
 * Format a session into a clean, authoritative text bulletin for copy/export/WhatsApp.
 */
export function formatSessionForExport(session, fallbackLocation = '') {
  if (!session || !Array.isArray(session.messages)) return '';

  const location = session.location || fallbackLocation || 'India';
  const timestamp = session.createdAtFormatted || formatIstTimestamp(new Date(session.createdAt || Date.now()));
  
  let bulletin = `🌤️ *WeatherGPT Meteorological Advisory Bulletin*\n`;
  bulletin += `📍 Location: ${location}\n`;
  bulletin += `🕒 Synchronized: ${timestamp}\n`;
  bulletin += `━━━━━━━━━━━━━━━━━━━━━\n\n`;

  session.messages.forEach((msg, idx) => {
    if (msg.role === 'user') {
      bulletin += `❓ *Query ${idx + 1}:* ${msg.text}\n\n`;
    } else if (msg.role === 'assistant') {
      bulletin += `📋 *Official Advisory:*\n${msg.text}\n`;
      if (msg.relevantStat) {
        bulletin += `📊 Parameter: ${msg.relevantStat}\n`;
      }
      if (msg.data?.temperature != null) {
        bulletin += `🌡️ Temp: ${msg.data.temperature}°C | 💧 Humidity: ${msg.data.humidity ?? '--'}% | 💨 Wind: ${msg.data.windSpeed ?? '--'} km/h\n`;
      }
      if (msg.advisory) {
        bulletin += `⚠️ Alert Note: ${msg.advisory}\n`;
      }
      bulletin += `━━━━━━━━━━━━━━━━━━━━━\n\n`;
    }
  });

  bulletin += `🌐 Generated by WeatherGPT • National Meteorological Early Warning & Multi-Model NWP Consensus`;
  return bulletin;
}

/**
 * Share formatted text via WhatsApp
 */
export function shareViaWhatsApp(text) {
  if (!text) return;
  const encoded = encodeURIComponent(text);
  const url = `https://api.whatsapp.com/send?text=${encoded}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

/**
 * Universal Share helper: triggers navigator.share if supported, or copies to clipboard
 */
export async function shareAnywhere(session, fallbackLocation = '') {
  const text = formatSessionForExport(session, fallbackLocation);
  if (!text) return false;
  if (typeof navigator !== 'undefined' && navigator.share) {
    try {
      await navigator.share({
        title: `WeatherGPT Advisory - ${session.location || fallbackLocation || 'Local'}`,
        text: text,
      });
      return true;
    } catch (err) {
      if (err.name !== 'AbortError') {
        try {
          await navigator.clipboard.writeText(text);
          return true;
        } catch (e) {}
      }
      return false;
    }
  } else if (typeof navigator !== 'undefined' && navigator.clipboard) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (e) {
      return false;
    }
  }
  return false;
}
